### ISSUE TITLE
junit5 compatible version

### ISSUE THREAD

**Issue by davidkarlsen** [stefanbirkner/fake-sftp-server-rule#11]
Would it be possible to alter the rule so that `@EnableRuleMigrationSupport` would work: https://medium.com/@GalletVictor/migration-from-junit-4-to-junit-5-d8fe38644abe
 - or better - make it an Extension?

**Comment by davidkarlsen** [comment]
Linking https://github.com/stefanbirkner/system-rules/issues/55

**Comment by stefanbirkner** [comment]
I would like to avoid it because it is only a hack that relies on a contract that is not really given (although it works for almost all rules that implement ExternalResource).

According to your comment in stefanbirkner/system-rules#55 the only problem why you cannot replace the rule with stefanbirkner/fake-sftp-server-lambda is that you need the port information before the test is started. Am I right?

**Comment by davidkarlsen** [comment]
Correct

**Comment by stefanbirkner** [comment]
How do you used to set the port for the SpringRunner with JUnit 4?

**Comment by davidkarlsen** [comment]
```
private static final String DHUB_ENDPOINT_PROPERTY = "dhub.sftp.endpoint";

    @ClassRule
    public static final FakeSftpServerRule sftpServer = new FakeSftpServerRule();

    @AfterAll
    public static void afterClass() {
        System.clearProperty(DHUB_ENDPOINT_PROPERTY);
    }

    @BeforeAll
    public static void beforeClass() {
        System.setProperty(DHUB_ENDPOINT_PROPERTY, "localhost:" + sftpServer.getPort());
    }
```

**Comment by stefanbirkner** [comment]
I have a workaround in mind. Give me a few minutes.

**Comment by stefanbirkner** [comment]
I have a workaround for the lambda solution

```java
private static final int String SFTP_SERVER_PORT = freePort();

@AfterAll
public static void afterClass() {
    System.clearProperty(DHUB_ENDPOINT_PROPERTY);
}

@BeforeAll
public static void beforeClass() {
    System.setProperty(DHUB_ENDPOINT_PROPERTY, "localhost:" + SFTP_SERVER_PORT);
}

@Test
void aTest() {
    withSftpServer(server -> {
        //your code
    });
}

private withSftpServer(
    FakeSftpServer.ExceptionThrowingConsumer testCode
) throws Exception {
    FakeSftpServer.withSftpServer(server -> {
        server.setPort(SFTP_SERVER_PORT);
        testCode.accept(server);
    });
}

private static freePort() {
    try (ServerSocket socket = new ServerSocket(0)) {
        return socket.getLocalPort();
    } catch (IOException e) {
        throw new RuntimeException(
            "Failed to find a free port.",
            e
        );
    }
}
```

Instead of the method `freePort` you may also use [Spring's SocketUtils.findAvailableTcpPort()](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/SocketUtils.html#findAvailableTcpPort--).

**Comment by sbrannen** [comment]
Glad you guys found a work-around! 🎉

**Comment by sbrannen** [comment]
And... I can also highly recommend Spring's `SocketUtils` (I promise: no personal bias).

**Comment by davidkarlsen** [comment]
It worked fine. Closing
