### ISSUE TITLE
Support Junit5 Jupiter

### ISSUE THREAD

**Issue by membersound** [stefanbirkner/fake-sftp-server-rule#19]
Are there any plans supporting junit 5 jupiter?

**Comment by jjkavalam** [comment]
Thinking out loud in terms of changes:
- provide a JUnit5 extension that implements the logic in `apply` https://github.com/stefanbirkner/fake-sftp-server-rule/blob/318473c9bc52fe99d37290a19b7d00b97389bf58/src/main/java/com/github/stefanbirkner/fakesftpserver/rule/FakeSftpServerRule.java#L395

Looks like that should do it ?

**Comment by stefanbirkner** [comment]
You may use [Fake SFTP Server Lambda](https://github.com/stefanbirkner/fake-sftp-server-lambda). It has the same functionality like Fake SFTP rule and can be used with JUnit Jupiter.
