### ISSUE TITLE
Support for user accounts/testing credentials

### ISSUE THREAD

**Issue by crizzis** [stefanbirkner/fake-sftp-server-rule#6]
It would be a nice feature if we could interact with the server using actual user credentials. 

At a minimum, the server could accept one specific set of credentials (rather than accepting any client-provided credentials). Alternatively, a flag could be set that indicates the server should now refuse any connection attempts, returning authorization error as the cause.

**Comment by stefanbirkner** [comment]
The feature is now available in release 1.4.0.
