### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by damian-cardozo-inmarsat** [stefanbirkner/fake-sftp-server-rule#8]
I'm gettin an error when trying to create a directory, put a file

Creating directory:

> Error auto creating directory: folder due File operation failed:  Could not parse response code.
> Server Reply: SSH-2.0-SSHD-CORE-1.7.0. Code: 0. This exception is ignored.

Reading file:

> Caused by: org.apache.commons.net.MalformedServerReplyException: Could not parse response code.
> Server Reply: SSH-2.0-SSHD-CORE-1.7.0

When disconnecting:

> Error occurred while disconnecting from ftps://admin@localhost:12345 due: File operation failed:  Could not parse response code.
> Server Reply: Unsupported protocol version: QUIT
> . Code: 0. This exception will be ignored.

This is how I declare it:

```
@Rule
    public final FakeSftpServerRule sftpServer = new FakeSftpServerRule()
            .setPort(12345)
            .addUser("admin", "admin");
```

and this is how I create folder and put file, in @PostConstruct method:

```
sftpServer.createDirectory("/folder");
        sftpServer.putFile("/folder/myfile_20180115082245.csv", CSV_CONTENTS, StandardCharsets.UTF_8);
```

The file is read by apache camel ftp, using this route:
ftps://admin@localhost:12345/folder?binary=true&connectTimeout=5000

**Comment by stefanbirkner** [comment]
I would like to help you, but I need more information. Can you create a minimal project that shows this errors?

**Comment by stefanbirkner** [comment]
Fake SFTP Server Rule creates an **SFTP** server but you're trying to use it with **FTPS** (FTP over SSL/TLS). These are two different protocols. You cannot use Fake SFTP Server Rule for testing your code.
